// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKNOWN                    ErrorCode = 0
	ErrorCode_INVALID_REQUEST            ErrorCode = 1
	ErrorCode_TENANT_NOT_FOUND           ErrorCode = 2
	ErrorCode_TENANT_EXISTS              ErrorCode = 3
	ErrorCode_KEY_NOT_FOUND              ErrorCode = 4
	ErrorCode_QUORUM_NOT_REACHED         ErrorCode = 5
	ErrorCode_IDEMPOTENCY_KEY_CONFLICT   ErrorCode = 6
	ErrorCode_INVALID_REPLICATION_FACTOR ErrorCode = 7
	ErrorCode_NODE_IN_USE                ErrorCode = 8
	ErrorCode_MIGRATION_NOT_FOUND        ErrorCode = 9
	ErrorCode_UNAUTHORIZED               ErrorCode = 10
	ErrorCode_FORBIDDEN                  ErrorCode = 11
	ErrorCode_RATE_LIMIT_EXCEEDED        ErrorCode = 12
	ErrorCode_INTERNAL_ERROR             ErrorCode = 13
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "INVALID_REQUEST",
		2:  "TENANT_NOT_FOUND",
		3:  "TENANT_EXISTS",
		4:  "KEY_NOT_FOUND",
		5:  "QUORUM_NOT_REACHED",
		6:  "IDEMPOTENCY_KEY_CONFLICT",
		7:  "INVALID_REPLICATION_FACTOR",
		8:  "NODE_IN_USE",
		9:  "MIGRATION_NOT_FOUND",
		10: "UNAUTHORIZED",
		11: "FORBIDDEN",
		12: "RATE_LIMIT_EXCEEDED",
		13: "INTERNAL_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":                    0,
		"INVALID_REQUEST":            1,
		"TENANT_NOT_FOUND":           2,
		"TENANT_EXISTS":              3,
		"KEY_NOT_FOUND":              4,
		"QUORUM_NOT_REACHED":         5,
		"IDEMPOTENCY_KEY_CONFLICT":   6,
		"INVALID_REPLICATION_FACTOR": 7,
		"NODE_IN_USE":                8,
		"MIGRATION_NOT_FOUND":        9,
		"UNAUTHORIZED":               10,
		"FORBIDDEN":                  11,
		"RATE_LIMIT_EXCEEDED":        12,
		"INTERNAL_ERROR":             13,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_coordinator_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_coordinator_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{0}
}

type VectorClockEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorNodeId string                 `protobuf:"bytes,1,opt,name=coordinator_node_id,json=coordinatorNodeId,proto3" json:"coordinator_node_id,omitempty"`
	LogicalTimestamp  int64                  `protobuf:"varint,2,opt,name=logical_timestamp,json=logicalTimestamp,proto3" json:"logical_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VectorClockEntry) Reset() {
	*x = VectorClockEntry{}
	mi := &file_api_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockEntry) ProtoMessage() {}

func (x *VectorClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockEntry.ProtoReflect.Descriptor instead.
func (*VectorClockEntry) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClockEntry) GetCoordinatorNodeId() string {
	if x != nil {
		return x.CoordinatorNodeId
	}
	return ""
}

func (x *VectorClockEntry) GetLogicalTimestamp() int64 {
	if x != nil {
		return x.LogicalTimestamp
	}
	return 0
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VectorClockEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_api_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *VectorClock) GetEntries() []*VectorClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WriteKeyValueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Consistency    string                 `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`                             // "one", "quorum", "all"
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Optional: client-provided idempotency key
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteKeyValueRequest) Reset() {
	*x = WriteKeyValueRequest{}
	mi := &file_api_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteKeyValueRequest) ProtoMessage() {}

func (x *WriteKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteKeyValueRequest.ProtoReflect.Descriptor instead.
func (*WriteKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *WriteKeyValueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WriteKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteKeyValueRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteKeyValueRequest) GetConsistency() string {
	if x != nil {
		return x.Consistency
	}
	return ""
}

func (x *WriteKeyValueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type WriteKeyValueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Server-generated if not provided
	VectorClock    *VectorClock           `protobuf:"bytes,4,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	ReplicaCount   int32                  `protobuf:"varint,5,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"` // Number of replicas that acknowledged
	Consistency    string                 `protobuf:"bytes,6,opt,name=consistency,proto3" json:"consistency,omitempty"`
	IsDuplicate    bool                   `protobuf:"varint,7,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"` // true if request was deduplicated
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteKeyValueResponse) Reset() {
	*x = WriteKeyValueResponse{}
	mi := &file_api_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteKeyValueResponse) ProtoMessage() {}

func (x *WriteKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteKeyValueResponse.ProtoReflect.Descriptor instead.
func (*WriteKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *WriteKeyValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteKeyValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteKeyValueResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WriteKeyValueResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *WriteKeyValueResponse) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *WriteKeyValueResponse) GetConsistency() string {
	if x != nil {
		return x.Consistency
	}
	return ""
}

func (x *WriteKeyValueResponse) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

func (x *WriteKeyValueResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReadKeyValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Consistency   string                 `protobuf:"bytes,3,opt,name=consistency,proto3" json:"consistency,omitempty"` // "one", "quorum", "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadKeyValueRequest) Reset() {
	*x = ReadKeyValueRequest{}
	mi := &file_api_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadKeyValueRequest) ProtoMessage() {}

func (x *ReadKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadKeyValueRequest.ProtoReflect.Descriptor instead.
func (*ReadKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ReadKeyValueRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReadKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadKeyValueRequest) GetConsistency() string {
	if x != nil {
		return x.Consistency
	}
	return ""
}

type ReadKeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,4,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadKeyValueResponse) Reset() {
	*x = ReadKeyValueResponse{}
	mi := &file_api_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadKeyValueResponse) ProtoMessage() {}

func (x *ReadKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadKeyValueResponse.ProtoReflect.Descriptor instead.
func (*ReadKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ReadKeyValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadKeyValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadKeyValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReadKeyValueResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

func (x *ReadKeyValueResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateTenantRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,2,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"` // Optional, default: 3
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_api_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type CreateTenantResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	ErrorMessage      string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_api_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTenantResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantResponse) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *CreateTenantResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateTenantResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateReplicationFactorRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TenantId             string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NewReplicationFactor int32                  `protobuf:"varint,2,opt,name=new_replication_factor,json=newReplicationFactor,proto3" json:"new_replication_factor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateReplicationFactorRequest) Reset() {
	*x = UpdateReplicationFactorRequest{}
	mi := &file_api_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationFactorRequest) ProtoMessage() {}

func (x *UpdateReplicationFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationFactorRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplicationFactorRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReplicationFactorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateReplicationFactorRequest) GetNewReplicationFactor() int32 {
	if x != nil {
		return x.NewReplicationFactor
	}
	return 0
}

type UpdateReplicationFactorResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TenantId             string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OldReplicationFactor int32                  `protobuf:"varint,3,opt,name=old_replication_factor,json=oldReplicationFactor,proto3" json:"old_replication_factor,omitempty"`
	NewReplicationFactor int32                  `protobuf:"varint,4,opt,name=new_replication_factor,json=newReplicationFactor,proto3" json:"new_replication_factor,omitempty"`
	MigrationId          string                 `protobuf:"bytes,5,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // If migration is triggered
	UpdatedAt            int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`      // Unix timestamp
	ErrorMessage         string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateReplicationFactorResponse) Reset() {
	*x = UpdateReplicationFactorResponse{}
	mi := &file_api_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicationFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicationFactorResponse) ProtoMessage() {}

func (x *UpdateReplicationFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicationFactorResponse.ProtoReflect.Descriptor instead.
func (*UpdateReplicationFactorResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateReplicationFactorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateReplicationFactorResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateReplicationFactorResponse) GetOldReplicationFactor() int32 {
	if x != nil {
		return x.OldReplicationFactor
	}
	return 0
}

func (x *UpdateReplicationFactorResponse) GetNewReplicationFactor() int32 {
	if x != nil {
		return x.NewReplicationFactor
	}
	return 0
}

func (x *UpdateReplicationFactorResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *UpdateReplicationFactorResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UpdateReplicationFactorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_api_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetTenantResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_api_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *GetTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenantResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantResponse) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *GetTenantResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTenantResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetTenantResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AddStorageNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	VirtualNodes  int32                  `protobuf:"varint,4,opt,name=virtual_nodes,json=virtualNodes,proto3" json:"virtual_nodes,omitempty"` // Number of virtual nodes (default: 150)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStorageNodeRequest) Reset() {
	*x = AddStorageNodeRequest{}
	mi := &file_api_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStorageNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNodeRequest) ProtoMessage() {}

func (x *AddStorageNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNodeRequest.ProtoReflect.Descriptor instead.
func (*AddStorageNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *AddStorageNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddStorageNodeRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddStorageNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddStorageNodeRequest) GetVirtualNodes() int32 {
	if x != nil {
		return x.VirtualNodes
	}
	return 0
}

type AddStorageNodeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId              string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MigrationId         string                 `protobuf:"bytes,3,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedCompletion int64                  `protobuf:"varint,5,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"` // Unix timestamp
	ErrorMessage        string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddStorageNodeResponse) Reset() {
	*x = AddStorageNodeResponse{}
	mi := &file_api_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStorageNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNodeResponse) ProtoMessage() {}

func (x *AddStorageNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNodeResponse.ProtoReflect.Descriptor instead.
func (*AddStorageNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *AddStorageNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddStorageNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddStorageNodeResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *AddStorageNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddStorageNodeResponse) GetEstimatedCompletion() int64 {
	if x != nil {
		return x.EstimatedCompletion
	}
	return 0
}

func (x *AddStorageNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RemoveStorageNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force removal without data migration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStorageNodeRequest) Reset() {
	*x = RemoveStorageNodeRequest{}
	mi := &file_api_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStorageNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStorageNodeRequest) ProtoMessage() {}

func (x *RemoveStorageNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStorageNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveStorageNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveStorageNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RemoveStorageNodeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveStorageNodeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId              string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MigrationId         string                 `protobuf:"bytes,3,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedCompletion int64                  `protobuf:"varint,5,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"` // Unix timestamp
	ErrorMessage        string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RemoveStorageNodeResponse) Reset() {
	*x = RemoveStorageNodeResponse{}
	mi := &file_api_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStorageNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStorageNodeResponse) ProtoMessage() {}

func (x *RemoveStorageNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStorageNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveStorageNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveStorageNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveStorageNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RemoveStorageNodeResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *RemoveStorageNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveStorageNodeResponse) GetEstimatedCompletion() int64 {
	if x != nil {
		return x.EstimatedCompletion
	}
	return 0
}

func (x *RemoveStorageNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetMigrationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationStatusRequest) Reset() {
	*x = GetMigrationStatusRequest{}
	mi := &file_api_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusRequest) ProtoMessage() {}

func (x *GetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *GetMigrationStatusRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type GetMigrationStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MigrationId         string                 `protobuf:"bytes,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "node_addition" or "node_deletion"
	NodeId              string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending", "in_progress", "completed", "failed", "cancelled"
	Progress            *MigrationProgress     `protobuf:"bytes,6,opt,name=progress,proto3" json:"progress,omitempty"`
	StartedAt           int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EstimatedCompletion int64                  `protobuf:"varint,8,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMigrationStatusResponse) Reset() {
	*x = GetMigrationStatusResponse{}
	mi := &file_api_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusResponse) ProtoMessage() {}

func (x *GetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *GetMigrationStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMigrationStatusResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *GetMigrationStatusResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMigrationStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetMigrationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMigrationStatusResponse) GetProgress() *MigrationProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetMigrationStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetEstimatedCompletion() int64 {
	if x != nil {
		return x.EstimatedCompletion
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MigrationProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeysMigrated  int64                  `protobuf:"varint,1,opt,name=keys_migrated,json=keysMigrated,proto3" json:"keys_migrated,omitempty"`
	TotalKeys     int64                  `protobuf:"varint,2,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationProgress) Reset() {
	*x = MigrationProgress{}
	mi := &file_api_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationProgress) ProtoMessage() {}

func (x *MigrationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationProgress.ProtoReflect.Descriptor instead.
func (*MigrationProgress) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *MigrationProgress) GetKeysMigrated() int64 {
	if x != nil {
		return x.KeysMigrated
	}
	return 0
}

func (x *MigrationProgress) GetTotalKeys() int64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *MigrationProgress) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ListStorageNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageNodesRequest) Reset() {
	*x = ListStorageNodesRequest{}
	mi := &file_api_coordinator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageNodesRequest) ProtoMessage() {}

func (x *ListStorageNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageNodesRequest.ProtoReflect.Descriptor instead.
func (*ListStorageNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{19}
}

type ListStorageNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Nodes         []*StorageNodeInfo     `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageNodesResponse) Reset() {
	*x = ListStorageNodesResponse{}
	mi := &file_api_coordinator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageNodesResponse) ProtoMessage() {}

func (x *ListStorageNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageNodesResponse.ProtoReflect.Descriptor instead.
func (*ListStorageNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{20}
}

func (x *ListStorageNodesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListStorageNodesResponse) GetNodes() []*StorageNodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListStorageNodesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StorageNodeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Host             string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port             int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active", "draining", "inactive"
	VirtualNodes     int32                  `protobuf:"varint,5,opt,name=virtual_nodes,json=virtualNodes,proto3" json:"virtual_nodes,omitempty"`
	KeysCount        int64                  `protobuf:"varint,6,opt,name=keys_count,json=keysCount,proto3" json:"keys_count,omitempty"`
	DiskUsagePercent float32                `protobuf:"fixed32,7,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageNodeInfo) Reset() {
	*x = StorageNodeInfo{}
	mi := &file_api_coordinator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNodeInfo) ProtoMessage() {}

func (x *StorageNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_coordinator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNodeInfo.ProtoReflect.Descriptor instead.
func (*StorageNodeInfo) Descriptor() ([]byte, []int) {
	return file_api_coordinator_proto_rawDescGZIP(), []int{21}
}

func (x *StorageNodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StorageNodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StorageNodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StorageNodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StorageNodeInfo) GetVirtualNodes() int32 {
	if x != nil {
		return x.VirtualNodes
	}
	return 0
}

func (x *StorageNodeInfo) GetKeysCount() int64 {
	if x != nil {
		return x.KeysCount
	}
	return 0
}

func (x *StorageNodeInfo) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

var File_api_coordinator_proto protoreflect.FileDescriptor

const file_api_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x15api/coordinator.proto\x12\x05proto\"o\n" +
	"\x10VectorClockEntry\x12.\n" +
	"\x13coordinator_node_id\x18\x01 \x01(\tR\x11coordinatorNodeId\x12+\n" +
	"\x11logical_timestamp\x18\x02 \x01(\x03R\x10logicalTimestamp\"@\n" +
	"\vVectorClock\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.proto.VectorClockEntryR\aentries\"\xa6\x01\n" +
	"\x14WriteKeyValueRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12 \n" +
	"\vconsistency\x18\x04 \x01(\tR\vconsistency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xb2\x02\n" +
	"\x15WriteKeyValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x125\n" +
	"\fvector_clock\x18\x04 \x01(\v2\x12.proto.VectorClockR\vvectorClock\x12#\n" +
	"\rreplica_count\x18\x05 \x01(\x05R\freplicaCount\x12 \n" +
	"\vconsistency\x18\x06 \x01(\tR\vconsistency\x12!\n" +
	"\fis_duplicate\x18\a \x01(\bR\visDuplicate\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"f\n" +
	"\x13ReadKeyValueRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12 \n" +
	"\vconsistency\x18\x03 \x01(\tR\vconsistency\"\xb4\x01\n" +
	"\x14ReadKeyValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x125\n" +
	"\fvector_clock\x18\x04 \x01(\v2\x12.proto.VectorClockR\vvectorClock\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"a\n" +
	"\x13CreateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12-\n" +
	"\x12replication_factor\x18\x02 \x01(\x05R\x11replicationFactor\"\xc0\x01\n" +
	"\x14CreateTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"s\n" +
	"\x1eUpdateReplicationFactorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x124\n" +
	"\x16new_replication_factor\x18\x02 \x01(\x05R\x14newReplicationFactor\"\xab\x02\n" +
	"\x1fUpdateReplicationFactorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x124\n" +
	"\x16old_replication_factor\x18\x03 \x01(\x05R\x14oldReplicationFactor\x124\n" +
	"\x16new_replication_factor\x18\x04 \x01(\x05R\x14newReplicationFactor\x12!\n" +
	"\fmigration_id\x18\x05 \x01(\tR\vmigrationId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xdc\x01\n" +
	"\x11GetTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"}\n" +
	"\x15AddStorageNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12#\n" +
	"\rvirtual_nodes\x18\x04 \x01(\x05R\fvirtualNodes\"\xe0\x01\n" +
	"\x16AddStorageNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fmigration_id\x18\x03 \x01(\tR\vmigrationId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\x14estimated_completion\x18\x05 \x01(\x03R\x13estimatedCompletion\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"I\n" +
	"\x18RemoveStorageNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xe3\x01\n" +
	"\x19RemoveStorageNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fmigration_id\x18\x03 \x01(\tR\vmigrationId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\x14estimated_completion\x18\x05 \x01(\x03R\x13estimatedCompletion\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\">\n" +
	"\x19GetMigrationStatusRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"\xcb\x02\n" +
	"\x1aGetMigrationStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fmigration_id\x18\x02 \x01(\tR\vmigrationId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x124\n" +
	"\bprogress\x18\x06 \x01(\v2\x18.proto.MigrationProgressR\bprogress\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x121\n" +
	"\x14estimated_completion\x18\b \x01(\x03R\x13estimatedCompletion\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"w\n" +
	"\x11MigrationProgress\x12#\n" +
	"\rkeys_migrated\x18\x01 \x01(\x03R\fkeysMigrated\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x02 \x01(\x03R\ttotalKeys\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"\x19\n" +
	"\x17ListStorageNodesRequest\"\x87\x01\n" +
	"\x18ListStorageNodesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05nodes\x18\x02 \x03(\v2\x16.proto.StorageNodeInfoR\x05nodes\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xdc\x01\n" +
	"\x0fStorageNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rvirtual_nodes\x18\x05 \x01(\x05R\fvirtualNodes\x12\x1d\n" +
	"\n" +
	"keys_count\x18\x06 \x01(\x03R\tkeysCount\x12,\n" +
	"\x12disk_usage_percent\x18\a \x01(\x02R\x10diskUsagePercent*\xb7\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x14\n" +
	"\x10TENANT_NOT_FOUND\x10\x02\x12\x11\n" +
	"\rTENANT_EXISTS\x10\x03\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x04\x12\x16\n" +
	"\x12QUORUM_NOT_REACHED\x10\x05\x12\x1c\n" +
	"\x18IDEMPOTENCY_KEY_CONFLICT\x10\x06\x12\x1e\n" +
	"\x1aINVALID_REPLICATION_FACTOR\x10\a\x12\x0f\n" +
	"\vNODE_IN_USE\x10\b\x12\x17\n" +
	"\x13MIGRATION_NOT_FOUND\x10\t\x12\x10\n" +
	"\fUNAUTHORIZED\x10\n" +
	"\x12\r\n" +
	"\tFORBIDDEN\x10\v\x12\x17\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\f\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\r2\xf3\x05\n" +
	"\x12CoordinatorService\x12J\n" +
	"\rWriteKeyValue\x12\x1b.proto.WriteKeyValueRequest\x1a\x1c.proto.WriteKeyValueResponse\x12G\n" +
	"\fReadKeyValue\x12\x1a.proto.ReadKeyValueRequest\x1a\x1b.proto.ReadKeyValueResponse\x12G\n" +
	"\fCreateTenant\x12\x1a.proto.CreateTenantRequest\x1a\x1b.proto.CreateTenantResponse\x12h\n" +
	"\x17UpdateReplicationFactor\x12%.proto.UpdateReplicationFactorRequest\x1a&.proto.UpdateReplicationFactorResponse\x12>\n" +
	"\tGetTenant\x12\x17.proto.GetTenantRequest\x1a\x18.proto.GetTenantResponse\x12M\n" +
	"\x0eAddStorageNode\x12\x1c.proto.AddStorageNodeRequest\x1a\x1d.proto.AddStorageNodeResponse\x12V\n" +
	"\x11RemoveStorageNode\x12\x1f.proto.RemoveStorageNodeRequest\x1a .proto.RemoveStorageNodeResponse\x12Y\n" +
	"\x12GetMigrationStatus\x12 .proto.GetMigrationStatusRequest\x1a!.proto.GetMigrationStatusResponse\x12S\n" +
	"\x10ListStorageNodes\x12\x1e.proto.ListStorageNodesRequest\x1a\x1f.proto.ListStorageNodesResponseB6Z4github.com/devrev/pairdb/api-gateway/pkg/proto;protob\x06proto3"

var (
	file_api_coordinator_proto_rawDescOnce sync.Once
	file_api_coordinator_proto_rawDescData []byte
)

func file_api_coordinator_proto_rawDescGZIP() []byte {
	file_api_coordinator_proto_rawDescOnce.Do(func() {
		file_api_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_coordinator_proto_rawDesc), len(file_api_coordinator_proto_rawDesc)))
	})
	return file_api_coordinator_proto_rawDescData
}

var file_api_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_coordinator_proto_goTypes = []any{
	(ErrorCode)(0),                          // 0: proto.ErrorCode
	(*VectorClockEntry)(nil),                // 1: proto.VectorClockEntry
	(*VectorClock)(nil),                     // 2: proto.VectorClock
	(*WriteKeyValueRequest)(nil),            // 3: proto.WriteKeyValueRequest
	(*WriteKeyValueResponse)(nil),           // 4: proto.WriteKeyValueResponse
	(*ReadKeyValueRequest)(nil),             // 5: proto.ReadKeyValueRequest
	(*ReadKeyValueResponse)(nil),            // 6: proto.ReadKeyValueResponse
	(*CreateTenantRequest)(nil),             // 7: proto.CreateTenantRequest
	(*CreateTenantResponse)(nil),            // 8: proto.CreateTenantResponse
	(*UpdateReplicationFactorRequest)(nil),  // 9: proto.UpdateReplicationFactorRequest
	(*UpdateReplicationFactorResponse)(nil), // 10: proto.UpdateReplicationFactorResponse
	(*GetTenantRequest)(nil),                // 11: proto.GetTenantRequest
	(*GetTenantResponse)(nil),               // 12: proto.GetTenantResponse
	(*AddStorageNodeRequest)(nil),           // 13: proto.AddStorageNodeRequest
	(*AddStorageNodeResponse)(nil),          // 14: proto.AddStorageNodeResponse
	(*RemoveStorageNodeRequest)(nil),        // 15: proto.RemoveStorageNodeRequest
	(*RemoveStorageNodeResponse)(nil),       // 16: proto.RemoveStorageNodeResponse
	(*GetMigrationStatusRequest)(nil),       // 17: proto.GetMigrationStatusRequest
	(*GetMigrationStatusResponse)(nil),      // 18: proto.GetMigrationStatusResponse
	(*MigrationProgress)(nil),               // 19: proto.MigrationProgress
	(*ListStorageNodesRequest)(nil),         // 20: proto.ListStorageNodesRequest
	(*ListStorageNodesResponse)(nil),        // 21: proto.ListStorageNodesResponse
	(*StorageNodeInfo)(nil),                 // 22: proto.StorageNodeInfo
}
var file_api_coordinator_proto_depIdxs = []int32{
	1,  // 0: proto.VectorClock.entries:type_name -> proto.VectorClockEntry
	2,  // 1: proto.WriteKeyValueResponse.vector_clock:type_name -> proto.VectorClock
	2,  // 2: proto.ReadKeyValueResponse.vector_clock:type_name -> proto.VectorClock
	19, // 3: proto.GetMigrationStatusResponse.progress:type_name -> proto.MigrationProgress
	22, // 4: proto.ListStorageNodesResponse.nodes:type_name -> proto.StorageNodeInfo
	3,  // 5: proto.CoordinatorService.WriteKeyValue:input_type -> proto.WriteKeyValueRequest
	5,  // 6: proto.CoordinatorService.ReadKeyValue:input_type -> proto.ReadKeyValueRequest
	7,  // 7: proto.CoordinatorService.CreateTenant:input_type -> proto.CreateTenantRequest
	9,  // 8: proto.CoordinatorService.UpdateReplicationFactor:input_type -> proto.UpdateReplicationFactorRequest
	11, // 9: proto.CoordinatorService.GetTenant:input_type -> proto.GetTenantRequest
	13, // 10: proto.CoordinatorService.AddStorageNode:input_type -> proto.AddStorageNodeRequest
	15, // 11: proto.CoordinatorService.RemoveStorageNode:input_type -> proto.RemoveStorageNodeRequest
	17, // 12: proto.CoordinatorService.GetMigrationStatus:input_type -> proto.GetMigrationStatusRequest
	20, // 13: proto.CoordinatorService.ListStorageNodes:input_type -> proto.ListStorageNodesRequest
	4,  // 14: proto.CoordinatorService.WriteKeyValue:output_type -> proto.WriteKeyValueResponse
	6,  // 15: proto.CoordinatorService.ReadKeyValue:output_type -> proto.ReadKeyValueResponse
	8,  // 16: proto.CoordinatorService.CreateTenant:output_type -> proto.CreateTenantResponse
	10, // 17: proto.CoordinatorService.UpdateReplicationFactor:output_type -> proto.UpdateReplicationFactorResponse
	12, // 18: proto.CoordinatorService.GetTenant:output_type -> proto.GetTenantResponse
	14, // 19: proto.CoordinatorService.AddStorageNode:output_type -> proto.AddStorageNodeResponse
	16, // 20: proto.CoordinatorService.RemoveStorageNode:output_type -> proto.RemoveStorageNodeResponse
	18, // 21: proto.CoordinatorService.GetMigrationStatus:output_type -> proto.GetMigrationStatusResponse
	21, // 22: proto.CoordinatorService.ListStorageNodes:output_type -> proto.ListStorageNodesResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_coordinator_proto_init() }
func file_api_coordinator_proto_init() {
	if File_api_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_coordinator_proto_rawDesc), len(file_api_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coordinator_proto_goTypes,
		DependencyIndexes: file_api_coordinator_proto_depIdxs,
		EnumInfos:         file_api_coordinator_proto_enumTypes,
		MessageInfos:      file_api_coordinator_proto_msgTypes,
	}.Build()
	File_api_coordinator_proto = out.File
	file_api_coordinator_proto_goTypes = nil
	file_api_coordinator_proto_depIdxs = nil
}
