// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/coordinator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_WriteKeyValue_FullMethodName           = "/proto.CoordinatorService/WriteKeyValue"
	CoordinatorService_ReadKeyValue_FullMethodName            = "/proto.CoordinatorService/ReadKeyValue"
	CoordinatorService_CreateTenant_FullMethodName            = "/proto.CoordinatorService/CreateTenant"
	CoordinatorService_UpdateReplicationFactor_FullMethodName = "/proto.CoordinatorService/UpdateReplicationFactor"
	CoordinatorService_GetTenant_FullMethodName               = "/proto.CoordinatorService/GetTenant"
	CoordinatorService_AddStorageNode_FullMethodName          = "/proto.CoordinatorService/AddStorageNode"
	CoordinatorService_RemoveStorageNode_FullMethodName       = "/proto.CoordinatorService/RemoveStorageNode"
	CoordinatorService_GetMigrationStatus_FullMethodName      = "/proto.CoordinatorService/GetMigrationStatus"
	CoordinatorService_ListStorageNodes_FullMethodName        = "/proto.CoordinatorService/ListStorageNodes"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoordinatorService handles coordination of distributed key-value operations
type CoordinatorServiceClient interface {
	// Key-Value Operations
	WriteKeyValue(ctx context.Context, in *WriteKeyValueRequest, opts ...grpc.CallOption) (*WriteKeyValueResponse, error)
	ReadKeyValue(ctx context.Context, in *ReadKeyValueRequest, opts ...grpc.CallOption) (*ReadKeyValueResponse, error)
	// Tenant Management
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	UpdateReplicationFactor(ctx context.Context, in *UpdateReplicationFactorRequest, opts ...grpc.CallOption) (*UpdateReplicationFactorResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	// Storage Node Management
	AddStorageNode(ctx context.Context, in *AddStorageNodeRequest, opts ...grpc.CallOption) (*AddStorageNodeResponse, error)
	RemoveStorageNode(ctx context.Context, in *RemoveStorageNodeRequest, opts ...grpc.CallOption) (*RemoveStorageNodeResponse, error)
	GetMigrationStatus(ctx context.Context, in *GetMigrationStatusRequest, opts ...grpc.CallOption) (*GetMigrationStatusResponse, error)
	ListStorageNodes(ctx context.Context, in *ListStorageNodesRequest, opts ...grpc.CallOption) (*ListStorageNodesResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) WriteKeyValue(ctx context.Context, in *WriteKeyValueRequest, opts ...grpc.CallOption) (*WriteKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteKeyValueResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_WriteKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReadKeyValue(ctx context.Context, in *ReadKeyValueRequest, opts ...grpc.CallOption) (*ReadKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadKeyValueResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ReadKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) UpdateReplicationFactor(ctx context.Context, in *UpdateReplicationFactorRequest, opts ...grpc.CallOption) (*UpdateReplicationFactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReplicationFactorResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_UpdateReplicationFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) AddStorageNode(ctx context.Context, in *AddStorageNodeRequest, opts ...grpc.CallOption) (*AddStorageNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddStorageNodeResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_AddStorageNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RemoveStorageNode(ctx context.Context, in *RemoveStorageNodeRequest, opts ...grpc.CallOption) (*RemoveStorageNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStorageNodeResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RemoveStorageNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetMigrationStatus(ctx context.Context, in *GetMigrationStatusRequest, opts ...grpc.CallOption) (*GetMigrationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationStatusResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetMigrationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ListStorageNodes(ctx context.Context, in *ListStorageNodesRequest, opts ...grpc.CallOption) (*ListStorageNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStorageNodesResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ListStorageNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
//
// CoordinatorService handles coordination of distributed key-value operations
type CoordinatorServiceServer interface {
	// Key-Value Operations
	WriteKeyValue(context.Context, *WriteKeyValueRequest) (*WriteKeyValueResponse, error)
	ReadKeyValue(context.Context, *ReadKeyValueRequest) (*ReadKeyValueResponse, error)
	// Tenant Management
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	UpdateReplicationFactor(context.Context, *UpdateReplicationFactorRequest) (*UpdateReplicationFactorResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	// Storage Node Management
	AddStorageNode(context.Context, *AddStorageNodeRequest) (*AddStorageNodeResponse, error)
	RemoveStorageNode(context.Context, *RemoveStorageNodeRequest) (*RemoveStorageNodeResponse, error)
	GetMigrationStatus(context.Context, *GetMigrationStatusRequest) (*GetMigrationStatusResponse, error)
	ListStorageNodes(context.Context, *ListStorageNodesRequest) (*ListStorageNodesResponse, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) WriteKeyValue(context.Context, *WriteKeyValueRequest) (*WriteKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteKeyValue not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReadKeyValue(context.Context, *ReadKeyValueRequest) (*ReadKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadKeyValue not implemented")
}
func (UnimplementedCoordinatorServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedCoordinatorServiceServer) UpdateReplicationFactor(context.Context, *UpdateReplicationFactorRequest) (*UpdateReplicationFactorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReplicationFactor not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedCoordinatorServiceServer) AddStorageNode(context.Context, *AddStorageNodeRequest) (*AddStorageNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStorageNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) RemoveStorageNode(context.Context, *RemoveStorageNodeRequest) (*RemoveStorageNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveStorageNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetMigrationStatus(context.Context, *GetMigrationStatusRequest) (*GetMigrationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMigrationStatus not implemented")
}
func (UnimplementedCoordinatorServiceServer) ListStorageNodes(context.Context, *ListStorageNodesRequest) (*ListStorageNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStorageNodes not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_WriteKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).WriteKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_WriteKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).WriteKeyValue(ctx, req.(*WriteKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReadKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReadKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReadKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReadKeyValue(ctx, req.(*ReadKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_UpdateReplicationFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReplicationFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).UpdateReplicationFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_UpdateReplicationFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).UpdateReplicationFactor(ctx, req.(*UpdateReplicationFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_AddStorageNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStorageNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).AddStorageNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_AddStorageNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).AddStorageNode(ctx, req.(*AddStorageNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RemoveStorageNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStorageNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RemoveStorageNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RemoveStorageNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RemoveStorageNode(ctx, req.(*RemoveStorageNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetMigrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetMigrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetMigrationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetMigrationStatus(ctx, req.(*GetMigrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ListStorageNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ListStorageNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ListStorageNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ListStorageNodes(ctx, req.(*ListStorageNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteKeyValue",
			Handler:    _CoordinatorService_WriteKeyValue_Handler,
		},
		{
			MethodName: "ReadKeyValue",
			Handler:    _CoordinatorService_ReadKeyValue_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _CoordinatorService_CreateTenant_Handler,
		},
		{
			MethodName: "UpdateReplicationFactor",
			Handler:    _CoordinatorService_UpdateReplicationFactor_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _CoordinatorService_GetTenant_Handler,
		},
		{
			MethodName: "AddStorageNode",
			Handler:    _CoordinatorService_AddStorageNode_Handler,
		},
		{
			MethodName: "RemoveStorageNode",
			Handler:    _CoordinatorService_RemoveStorageNode_Handler,
		},
		{
			MethodName: "GetMigrationStatus",
			Handler:    _CoordinatorService_GetMigrationStatus_Handler,
		},
		{
			MethodName: "ListStorageNodes",
			Handler:    _CoordinatorService_ListStorageNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/coordinator.proto",
}
